from training_cards.schemas import CardRelationship, CardReference, CardType, MicroCard, TrainingLevel

recovery_week = MicroCard(
    id = "micro_001",
    slug = "recovery-week",
    title = "Recovery Week",
    card_type = CardType.MICRO,
    suitable_levels = [TrainingLevel.ALL],
    summary = "A reduced-load week that restores readiness before the next training emphasis.",
    purpose = "Lower fatigue while preserving routine and easy movement.",
    detailed_description = "Use this week after demanding training, racing, travel, or when fatigue markers are rising. The goal is to feel better by the end of the week, not to prove fitness. Trail runners should reduce downhill and technical load first when mechanical soreness is the main problem.",
    tags = ["recovery", "deload", "fatigue_management"],
    goal_race_context = ["Fits any goal when recovery is needed."],
    when_to_choose = ["After two to four harder weeks.", "When soreness, mood, or easy effort suggest accumulated fatigue."],
    when_not_to_choose = ["Do not use as total inactivity unless rest is clearly needed.", "Do not ignore persistent pain or illness."],
    expected_adaptations = ["Reduced fatigue.", "Improved readiness for the next week.", "Better consistency across the full plan."],
    training_characteristics = ["Lower volume.", "Easy running only or very light strides.", "Optional mobility, walking, or cross-training."],
    terrain_demands = ["Use forgiving terrain.", "Avoid hard downhill or technical running if soreness is present."],
    common_mistakes = ["Keeping intensity high because volume is lower.", "Adding extra strength work because the week feels easy."],
    warning_signs = ["Fatigue does not improve.", "Easy running feels worse across the week."],
    progression_rules = ["Return to normal training when easy movement feels normal."],
    regression_rules = ["Replace running with walking or rest if easy running is not restorative."],
    references = [
        CardReference(card_id = "mezzo_009", relationship = CardRelationship.PARENT, tags = ["core_week"]),
        CardReference(card_id = "session_002", relationship = CardRelationship.CHILD, tags = ["core_session"]),
        CardReference(card_id = "session_001", relationship = CardRelationship.CHILD, tags = ["optional"]),
    ],
    recommended_duration_days = "7",
    week_structure = ["Mostly rest, recovery runs, or short easy runs.", "No demanding key workout."],
    key_sessions = ["Recovery Run", "Easy Run"],
    load_pattern = "Reduced load.",
    placement_guidance = ["Use after high-load weeks or before another demanding block."],
    recovery_requirements = ["Sleep, easy effort, and soreness should improve by the end of the week."],
)

