from training_cards.schemas import CardRelationship, CardReference, CardType, MicroCard, TrainingLevel

taper_week = MicroCard(
    id = "micro_009",
    slug = "taper-week",
    title = "Taper Week",
    card_type = CardType.MICRO,
    suitable_levels = [TrainingLevel.ALL],
    summary = "A reduced-load week that preserves rhythm and freshness before a goal event.",
    purpose = "Arrive rested without becoming flat or anxious.",
    detailed_description = "The taper week is about protecting freshness. Short light intensity can maintain rhythm, but the athlete should avoid last-minute fitness tests. Trail runners should avoid risky technical terrain and hard descending close to race day.",
    tags = ["taper", "freshness", "race_week"],
    goal_race_context = ["Useful immediately before a goal race."],
    when_to_choose = ["When race day is near and preparation is mostly complete."],
    when_not_to_choose = ["Do not use if the event is not important enough to justify a taper.", "Do not use to cram missed training."],
    expected_adaptations = ["Reduced fatigue.", "Maintained readiness.", "Improved race-day freshness."],
    training_characteristics = ["Reduced volume.", "Short controlled rhythm touches.", "No major new stress."],
    terrain_demands = ["Use familiar low-risk terrain.", "Trail runners should limit hard downhill and technical risk."],
    common_mistakes = ["Testing fitness.", "Resting so much the athlete feels flat.", "Changing gear or fueling late."],
    warning_signs = ["Anxiety-driven extra training.", "New soreness from unnecessary efforts."],
    progression_rules = ["Keep sessions short and confidence-building."],
    regression_rules = ["Reduce further if fatigue, soreness, or illness appears."],
    references = [
        CardReference(card_id = "macro_005", relationship = CardRelationship.PARENT, tags = ["race_week"]),
        CardReference(card_id = "session_001", relationship = CardRelationship.CHILD, tags = ["core_session"]),
        CardReference(card_id = "session_011", relationship = CardRelationship.CHILD, tags = ["rhythm"]),
    ],
    recommended_duration_days = "7",
    week_structure = ["Short easy runs.", "Optional brief rhythm work.", "Rest or shakeout before race as appropriate."],
    key_sessions = ["Easy Run", "Strides"],
    load_pattern = "Reduced race-week load.",
    placement_guidance = ["Use in the final week before a goal event."],
    recovery_requirements = ["Freshness is the priority over any extra fitness stimulus."],
)

