from training_cards.schemas import CardRelationship, CardReference, CardType, SessionCard, SessionPart, TrainingLevel

steady_run = SessionCard(
    id = "session_005",
    slug = "steady-run",
    title = "Steady Run",
    card_type = CardType.SESSION,
    suitable_levels = [TrainingLevel.ALL],
    summary = "A controlled aerobic run slightly stronger than easy effort.",
    purpose = "Build aerobic stamina without the cost of a true threshold workout.",
    detailed_description = "Steady running can be useful, but it is easy to overuse. It should be clearly controlled and not replace easy volume. Trail runners can use effort on rolling terrain, but should avoid letting climbs push the session into threshold.",
    tags = ["steady", "aerobic", "stamina"],
    goal_race_context = ["Useful in base, build, or race-specific phases when controlled stamina is needed."],
    when_to_choose = ["When the athlete needs a moderate aerobic stimulus.", "When full threshold work is not needed."],
    when_not_to_choose = ["Do not use too often if it crowds out easy recovery."],
    expected_adaptations = ["Aerobic stamina.", "Effort control."],
    training_characteristics = ["Sustained controlled effort.", "Lower cost than threshold."],
    terrain_demands = ["Choose terrain where effort stays stable."],
    common_mistakes = ["Letting steady become hard.", "Doing too many moderate days."],
    warning_signs = ["Easy days become stale.", "Steady pace drifts into strain."],
    progression_rules = ["Extend duration before increasing effort."],
    regression_rules = ["Convert to easy run if fatigue is present."],
    references = [CardReference(card_id = "micro_002", relationship = CardRelationship.PARENT, tags = ["option"])],
    session_family = "steady",
    typical_duration = "30-90 minutes",
    workout_parts = [
        SessionPart(name = "Warm-Up", duration = "10-20 min", rpe = "2-3", instructions = "Start easy."),
        SessionPart(name = "Steady Aerobic Running", duration = "20-60 min", rpe = "5-6", instructions = "Stay controlled and below threshold.", terrain_notes = "On rolling trails, judge by breathing and effort rather than pace."),
        SessionPart(name = "Cool Down", duration = "5-15 min", rpe = "2-3", instructions = "Return to easy running."),
    ],
    intensity_guidance = ["Moderate but controlled.", "Below threshold."],
    execution_notes = ["Keep the session repeatable."],
    recovery_requirements = ["Usually modest if controlled."],
)

